openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /cake:
    get:
      description: return list of all available cakes
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/cakes'


components:
  schemas:
    cakes:
      additionalProperties: false
      type: object
      properties:
        cake_list:
          type: array
          items:
              $ref: '#/components/schemas/cake'

    cake:
      type: object
      description: Short info about cakes
      required:
        - id
        - name
        - calories
        - image
        - price
        - weight
      properties:
        id:
         type: number
         description: Id of object
        name:
          type: string
          description: Name of object
        calories:
          type: number
          description: Calories of cake
        image:
          type: string
          description: Relative url of image
        price:
          type: number
          description: Price of cake
        weight:
          type: number
          description: Weight of cake
  
